apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  # used 3 replicas in order to have alwayas majority for leader election
  replicas: 3
  template:
    metadata:
      labels:
        name: kafka
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
       - name: volume-mount-hack
         image: busybox
         command: ["sh", "-c", "chown -R 1001:1001 /var/kafka/"]
         volumeMounts:
           - name: kafka-storage
             mountPath: /var/kafka/
      containers:
        - name: kafka
          image: "enmasseproject/kafka-statefulsets:latest"
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/kafka/
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
