apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /var/zookeeper/"]
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/zookeeper
      containers:
        - name: zookeeper
          image: "enmasseproject/zookeeper:latest"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
