apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-connect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: enmasseproject/kafka-connect:latest
          ports:
            - name: rest-api
              containerPort: 8083
              protocol: TCP
          command:
            - /opt/kafka/kafka_connect_run.sh
          env:
            - name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
              value: "${KAFKA_CONNECT_BOOTSTRAP_SERVERS}"
            - name: KAFKA_CONNECT_GROUP_ID
              value: "${KAFKA_CONNECT_GROUP_ID}"
            - name: KAFKA_CONNECT_KEY_CONVERTER
              value: "${KAFKA_CONNECT_KEY_CONVERTER}"
            - name: KAFKA_CONNECT_VALUE_CONVERTER
              value: "${KAFKA_CONNECT_VALUE_CONVERTER}"
          livenessProbe:
            httpGet:
              path: /
              port: rest-api
            initialDelaySeconds: 60