apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "ppatierno/barnabas:0.1"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
          command:
            - /opt/kafka_2.11-0.10.1.1/zookeeper_run.sh
          volumeMounts:
            - name: zookeeper-persistent-storage
              mountPath: /tmp/zookeeper
          livenessProbe:
              tcpSocket:
                port: clientport
      volumes:
        - name: zookeeper-persistent-storage
          persistentVolumeClaim:
            claimName: zookeeperclaim
