apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper3
spec:
  replicas: 1
  selector:
    name: zookeeper3
  template:
    metadata:
      labels:
        name: zookeeper3
    spec:
      containers:
        - name: zookeeper3
          image: "ppatierno/barnabas:0.1"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
            - name: followerport
              containerPort: 2888
              protocol: TCP
            - name: leaderport
              containerPort: 3888
              protocol: TCP
          command:
            - /opt/kafka_2.11-0.10.1.1/zookeeper_run.sh
          env:
            - name: ZOOKEEPER_ID
              value: "3"
          volumeMounts:
            - name: zookeeper-persistent-storage
              mountPath: /tmp/zookeeper
          livenessProbe:
              tcpSocket:
                port: clientport
      volumes:
        - name: zookeeper-persistent-storage
          persistentVolumeClaim:
            claimName: zookeeperclaim
