apiVersion: v1
kind: Service
metadata:
  name: zookeeper3
spec:
  ports:
    - port: 2181
      name: clientport
      targetPort : 2181
      protocol: TCP
    - port: 2888
      name: followerport
      targetPort: 2888
      protocol: TCP
    - port: 3888
      name: leaderport
      targetPort: 3888
      protocol: TCP
  selector:
    name: zookeeper3
