apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kafka
spec:
  # used 3 replicas in order to have alwayas majority for leader election
  replicas: 3
  selector:
    name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
          - name: kafka
            image: "ppatierno/barnabas:0.1"
            ports:
              - containerPort: 9092
                protocol: TCP
            command:
              - /opt/kafka_2.11-0.10.1.1/kafka_run.sh
            volumeMounts:
              - name: kafka-persistent-storage
                mountPath: /tmp/kafka/
            lifecycle:
              preStop:
                exec:
                  command:
                    - /opt/kafka_2.11-0.10.1.1/bin/kafka-server-stop.sh
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafkaclaim
