apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostpath-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hostpath-provisioner
    spec:
      containers:
        - name: hostpath-provisioner
          image: ppatierno/hostpath-provisioner:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: pv-volume
              mountPath: /tmp/hostpath-provisioner
      serviceAccount: hostpath-provisioner
      volumes:
        - name: pv-volume
          hostPath:
            path: /tmp/hostpath-provisioner
