apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "enmasseproject/kafka-statefulsets:latest"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /tmp/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "example-hostpath"
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
