apiVersion: v1
kind: PersistentVolume
metadata:
    name: zookeeperpv
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: /tmp/zookeeper