apiVersion: v1
kind: ReplicationController
metadata:
    name: zookeeper
spec:
    replicas: 1
    selector:
        name: zookeeper
    template:
        metadata:
            labels:
                name: zookeeper
        spec:
            containers:
                -
                    name: zookeeper
                    image: "ppatierno/kaas:0.1"
                    ports:
                        - containerPort: 2181
                    command:
                        - /opt/kafka_2.11-0.9.0.1/bin/zookeeper-server-start.sh
                        - /opt/kafka_2.11-0.9.0.1/config/zookeeper.properties
                    