apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      securityContext:
        fsGroup: 996
      containers:
        - name: zookeeper
          image: "enmasseproject/zookeeper:latest"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /tmp/zookeeper
          livenessProbe:
              tcpSocket:
                port: clientport
      volumes:
        - name: zookeeper-storage
          emptyDir: {}
