apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  # used 3 replicas in order to have alwayas majority for leader election
  replicas: 3
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka
          image: "enmasseproject/kafka-persisted:latest"
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          command:
            - /opt/kafka/kafka_run.sh
          volumeMounts:
            - name: kafka-persistent-storage
              mountPath: /tmp/kafka/
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/kafka/bin/kafka-server-stop.sh
          livenessProbe:
              tcpSocket:
                port: kafka
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafkaclaim
