apiVersion: v1
kind: Template
metadata:
  name: barnabas-connect-s2i
parameters:
- description: Specifies the name of the Build which will be created by this template
  displayName: Name of the Build
  name: BUILD_NAME
  required: true
  value: "kafka-connect"
- description: Specifies the name of the new Kafka Connect Docker image which will be generated
  displayName: Name of the newly generated Docker image
  name: TARGET_IMAGE_NAME
  required: true
  value: "kafka-connect"
- description: Image repository name of the source S2I Docker image
  displayName: Repository Name of the S2I image
  name: S2I_IMAGE_REPO_NAME
  value: enmasseproject 
- description: Name of the source S2I Docker image
  displayName: Name of the S2I image
  name: S2I_IMAGE_NAME
  value: kafka-connect-s2i
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${TARGET_IMAGE_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${S2I_IMAGE_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: ${S2I_IMAGE_REPO_NAME}/${S2I_IMAGE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${BUILD_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${TARGET_IMAGE_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${S2I_IMAGE_NAME}:latest
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
