apiVersion: v1
kind: Template
metadata:
  name: barnabas-connect-s2i
parameters:
- description: Name of the Build which will be created by this template
  displayName: Build name
  name: BUILD_NAME
  required: true
  value: "kafka-connect"
- description: Name of the new Kafka Connect Docker image which will be generated
  displayName: Target image name
  name: TARGET_IMAGE_NAME
  required: true
  value: "kafka-connect"
- description: Tag of the new Kafka Connect Docker image which will be generated
  displayName: Target image tag
  name: TARGET_IMAGE_TAG
  value: latest
- description: Image repository name of the S2I Docker image
  displayName: S2I image repository
  name: S2I_IMAGE_REPO_NAME
  value: enmasseproject 
- description: Name of the S2I Docker image
  displayName: S2I image name
  name: S2I_IMAGE_NAME
  value: kafka-connect-s2i
- description: Tag of the S2I Docker image
  displayName: S2I image tag
  name: S2I_IMAGE_TAG
  value: latest
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${TARGET_IMAGE_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${S2I_IMAGE_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: ${S2I_IMAGE_REPO_NAME}/${S2I_IMAGE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${BUILD_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${TARGET_IMAGE_NAME}:${TARGET_IMAGE_TAG}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${S2I_IMAGE_NAME}:${S2I_IMAGE_TAG}
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
